<Project>
  <PropertyGroup>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>

    <DisableImplicitNuGetFallbackFolder>true</DisableImplicitNuGetFallbackFolder>
    
    <RestoreLockedMode>false</RestoreLockedMode>
    
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
</Project>