<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\FartiksPlatform.Services.Gameplay.Domain\FartiksPlatform.Services.Gameplay.Domain.csproj" />
    <ProjectReference Include="..\..\..\FartiksPlatform.BuildingBlocks\FartiksPlatform.BuildingBlocks.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
